<?php if (isset($notifications)): ?>
<br>
    <?php foreach ($notifications as $notification) : ?>
        <div class="alert alert-danger" role="alert">
            <?php echo $notification; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
<h1 class="my-4">Registration</h1>
<div class="card">
    <div class="card-body">
        <form method="post">
            <div class="form-group my-3">
                <label for="username">Username:</label>
                <input type="text" class="form-control" name="username">
                <small class="form-text text-muted">required, 8 - 20 characters, unique</small>
            </div>
            <div class="form-group my-3">
                <label for="email">Email address:</label>
                <input type="email" class="form-control" name="email">
                <small class="form-text text-muted">required, 40 characters maximum, email, unique</small>
            </div>
            <div class="form-group my-3">
                <label for="password">Password:</label>
                <input type="password" class="form-control" name="password">
                <small class="form-text text-muted">required, 8 characters minimum</small>
            </div>
            <div class="form-group my-3">
                <label for="confirm_password">Confirm Password:</label>
                <input type="password" class="form-control" name="confirm_password">
                <small class="form-text text-muted">required, confirm password</small>
            </div>
            <button type="submit" class="btn btn-outline-secondary my-3" name="submit" >Submit</button>
        </form>
    </div>
</div>
